#Question 1

In [ ]:
import numpy as np

In [27]:
a=np.random.rand(3,3)
b=np.random.rand(3,3)

In [28]:
a

array([[0.55293304, 0.58242742, 0.62929567],
       [0.37006861, 0.11738995, 0.71353995],
       [0.09378754, 0.88453847, 0.33353285]])

In [29]:
b

array([[0.9487902 , 0.19068358, 0.58578261],
       [0.01014706, 0.25434337, 0.87112516],
       [0.74545365, 0.77230317, 0.65200022]])

In [30]:
a+b

array([[1.50172324, 0.77311101, 1.21507828],
       [0.38021567, 0.37173333, 1.58466511],
       [0.8392412 , 1.65684164, 0.98553307]])

In [31]:
a-b

array([[-0.39585716,  0.39174384,  0.04351306],
       [ 0.35992155, -0.13695342, -0.15758521],
       [-0.65166611,  0.1122353 , -0.31846737]])

In [32]:
a*b

array([[0.52461745, 0.11105935, 0.36863046],
       [0.00375511, 0.02985736, 0.6215826 ],
       [0.06991427, 0.68313186, 0.21746349]])

In [33]:
a/b

array([[ 0.58277693,  3.05441829,  1.07428193],
       [36.47052336,  0.46154123,  0.81910153],
       [ 0.12581271,  1.14532545,  0.51155329]])

In [34]:
a.dot(b)

array([[0.99963813, 0.73957885, 1.24156666],
       [0.8842196 , 0.65149253, 0.7842693 ],
       [0.34659345, 0.50044873, 1.04294632]])

#Question 2

In [36]:
a=np.random.rand(3,4)

In [37]:
a

array([[0.02455617, 0.14792906, 0.89709541, 0.36377234],
       [0.25340608, 0.40889077, 0.21737684, 0.56598665],
       [0.24833029, 0.13365224, 0.7601126 , 0.32288831]])

In [38]:
a.mean()

0.36199972909018313

In [42]:
np.median(a)

0.28814719449781184

In [65]:
from scipy import stats as st
import numpy as np
st.mode(a)

/tmp/ipykernel_96325/2959266401.py:3: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  st.mode(a)


ModeResult(mode=array([[0.02455617, 0.13365224, 0.21737684, 0.32288831]]), count=array([[1, 1, 1, 1]]))

In [66]:
np.min(a)

0.02455616789818027

In [67]:
np.max(a)

0.8970954129481241

In [68]:
a.std()

0.24960462241362597

In [69]:
np.std(a)

0.24960462241362597