In [4]:

import numpy as np 
from numpy import linalg 
  

matrix = np.array([[1, 3], [3, 6]]) 
print("Original  matrix") 
print(matrix) 
  

print("Determinant of the matrix:") 
print(np.linalg.det(matrix))

Original  matrix
[[1 3]
 [3 6]]
Determinant of the matrix:
-3.0000000000000004


In [5]:


A = np.array([[6, 1, 9],
              [7, 2, 2],
              [2, 4, 7]])
 

print(np.linalg.inv(A))

[[ 0.02898551  0.14009662 -0.07729469]
 [-0.2173913   0.11594203  0.24637681]
 [ 0.11594203 -0.10628019  0.02415459]]


In [7]:

m = np.array([[1, 2], 
              [2, 3]]) 
  
print("Printing the Original square array:\n", 
      m) 
  
w, v = np.linalg.eig(m) 

print(" Eigen values of the given square array:\n", 
      w) 
  

print(" eigenvectors of the given square array:\n",
      v)

Printing the Original square array:
 [[1 2]
 [2 3]]
 Eigen values of the given square array:
 [-0.23606798  4.23606798]
 eigenvectors of the given square array:
 [[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]


In [17]:

a = ([7, 6, 5],[4,4, 8],[2, 12, 3])
b = ([13, 14, 16],[15, 16, 17],[16,56, 27])


mult = np.multiply(a,b)


print(mult)

[[ 91  84  80]
 [ 60  64 136]
 [ 32 672  81]]


In [11]:
a = ([7, 6, 5],[4,4, 8],[2, 12, 3])
b = ([13, 14, 16],[15, 16, 17],[16,56, 27])


ADD = np.add(a,b)


print(ADD)

[[20 20 21]
 [19 20 25]
 [18 68 30]]


In [13]:
a = ([7, 6, 5],[4,4, 8],[2, 12, 3])
b = ([13, 14, 16],[15, 16, 17],[16,56, 27])


sub = np.subtract(a,b)


print(sub)

[[ -6  -8 -11]
 [-11 -12  -9]
 [-14 -44 -24]]


In [18]:
a = ([7, 6, 5],[4,4, 8],[2, 12, 3])
b = ([13, 14, 16],[15, 16, 17],[16,56, 27])


sub = np.subtract(a,b)


print(sub)

[[ -6  -8 -11]
 [-11 -12  -9]
 [-14 -44 -24]]


In [25]:
a = ([7, 6, 5],[4,4, 8],[2, 12, 3])
b = ([13, 14, 16],[15, 16, 17],[16,56, 27])


T = np.transpose(a)
T2 = np.transpose(b)


print(T)
print(T2)

[[ 7  4  2]
 [ 6  4 12]
 [ 5  8  3]]
[[13 15 16]
 [14 16 56]
 [16 17 27]]


In [26]:
a = ([7, 6, 5],[4,4, 8],[2, 12, 3])
b = ([13, 14, 16],[15, 16, 17],[16,56, 27])


d = np.dot(a,b)


print(d)


[[261 474 349]
 [240 568 348]
 [254 388 317]]
