In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
x= np.array([4,11,15,21,28,34,39,35,47,55])
y= np.array([10,22,31,36,48,51,58,61,69,77])
z= np.array([92,83,89,56,61,56,48,41,26,19])
p= np.array([56,44,27,65,38,61,23,75,36,58])

In [4]:
df= pd.DataFrame({
    'X' : x,
    'Y' : y,
    'Z' : z,
    'P' : p
})

In [5]:
df

X   Y   Z   P
0   4  10  92  56
1  11  22  83  44
2  15  31  89  27
3  21  36  56  65
4  28  48  61  38
5  34  51  56  61
6  39  58  48  23
7  35  61  41  75
8  47  69  26  36
9  55  77  19  58

In [6]:
df.corr()

X         Y         Z         P
X  1.000000  0.988286 -0.959855  0.024336
Y  0.988286  1.000000 -0.952646  0.041168
Z -0.959855 -0.952646  1.000000 -0.200311
P  0.024336  0.041168 -0.200311  1.000000

In [7]:
#mtcars.csv

In [8]:
df=pd.read_csv('mtcars.csv')

In [12]:
df

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0   21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1   21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2   22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3   21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4   18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2
5   18.1    6  225.0  105  2.76  3.460  20.22   1   0     3     1
6   14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4
7   24.4    4  146.7   62  3.69  3.190  20.00   1   0     4     2
8   22.8    4  140.8   95  3.92  3.150  22.90   1   0     4     2
9   19.2    6  167.6  123  3.92  3.440  18.30   1   0     4     4
10  17.8    6  167.6  123  3.92  3.440  18.90   1   0     4     4
11  16.4    8  275.8  180  3.07  4.070  17.40   0   0     3     3
12  17.3    8  275.8  180  3.07  3.730  17.60   0   0     3     3
13  15.2    8  275.8  180  3.07  3.780  18.00   0   0     3     3
14  10.4    8  472.0  205  2.93  5.250  17.98   0   0     3     4
15  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3     4
16  14.7    8  440.0  230  3.23  5.345  17.42   0   0     3     4
17  32.4    4   78.7   66  4.08  2.200  19.47   1   1     4     1
18  30.4    4   75.7   52  4.93  1.615  18.52   1   1     4     2
19  33.9    4   71.1   65  4.22  1.835  19.90   1   1     4     1
20  21.5    4  120.1   97  3.70  2.465  20.01   1   0     3     1
21  15.5    8  318.0  150  2.76  3.520  16.87   0   0     3     2
22  15.2    8  304.0  150  3.15  3.435  17.30   0   0     3     2
23  13.3    8  350.0  245  3.73  3.840  15.41   0   0     3     4
24  19.2    8  400.0  175  3.08  3.845  17.05   0   0     3     2
25  27.3    4   79.0   66  4.08  1.935  18.90   1   1     4     1
26  26.0    4  120.3   91  4.43  2.140  16.70   0   1     5     2
27  30.4    4   95.1  113  3.77  1.513  16.90   1   1     5     2
28  15.8    8  351.0  264  4.22  3.170  14.50   0   1     5     4
29  19.7    6  145.0  175  3.62  2.770  15.50   0   1     5     6
30  15.0    8  301.0  335  3.54  3.570  14.60   0   1     5     8
31  21.4    4  121.0  109  4.11  2.780  18.60   1   1     4     2

In [ ]:
%precision 2
for i in range(len(correlation_matrix)):
    for j in range(i):
        if  abs(correlation_matrix.iloc[i,j])>0.8:
            correlated_featurs.add(correlation_matrix.columns[i])

In [ ]:
corr

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
df=pd.read_csv('mtcars.csv')

In [5]:
df

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0   21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1   21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2   22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3   21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4   18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2
5   18.1    6  225.0  105  2.76  3.460  20.22   1   0     3     1
6   14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4
7   24.4    4  146.7   62  3.69  3.190  20.00   1   0     4     2
8   22.8    4  140.8   95  3.92  3.150  22.90   1   0     4     2
9   19.2    6  167.6  123  3.92  3.440  18.30   1   0     4     4
10  17.8    6  167.6  123  3.92  3.440  18.90   1   0     4     4
11  16.4    8  275.8  180  3.07  4.070  17.40   0   0     3     3
12  17.3    8  275.8  180  3.07  3.730  17.60   0   0     3     3
13  15.2    8  275.8  180  3.07  3.780  18.00   0   0     3     3
14  10.4    8  472.0  205  2.93  5.250  17.98   0   0     3     4
15  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3     4
16  14.7    8  440.0  230  3.23  5.345  17.42   0   0     3     4
17  32.4    4   78.7   66  4.08  2.200  19.47   1   1     4     1
18  30.4    4   75.7   52  4.93  1.615  18.52   1   1     4     2
19  33.9    4   71.1   65  4.22  1.835  19.90   1   1     4     1
20  21.5    4  120.1   97  3.70  2.465  20.01   1   0     3     1
21  15.5    8  318.0  150  2.76  3.520  16.87   0   0     3     2
22  15.2    8  304.0  150  3.15  3.435  17.30   0   0     3     2
23  13.3    8  350.0  245  3.73  3.840  15.41   0   0     3     4
24  19.2    8  400.0  175  3.08  3.845  17.05   0   0     3     2
25  27.3    4   79.0   66  4.08  1.935  18.90   1   1     4     1
26  26.0    4  120.3   91  4.43  2.140  16.70   0   1     5     2
27  30.4    4   95.1  113  3.77  1.513  16.90   1   1     5     2
28  15.8    8  351.0  264  4.22  3.170  14.50   0   1     5     4
29  19.7    6  145.0  175  3.62  2.770  15.50   0   1     5     6
30  15.0    8  301.0  335  3.54  3.570  14.60   0   1     5     8
31  21.4    4  121.0  109  4.11  2.780  18.60   1   1     4     2

In [7]:
x= df.drop('mpg',axis =1)

In [8]:
correlation_matrix=x.corr()
correlated_featurs=set()

In [9]:
%precision 2
for i in range(len(correlation_matrix)):
    for j in range(i):
        if  abs(correlation_matrix.iloc[i,j])>0.8:
            correlated_featurs.add(correlation_matrix.columns[i])

In [10]:
df.drop(correlated_featurs, axis=1, inplace=True)

In [11]:
df

mpg  cyl  drat   qsec  am  gear  carb
0   21.0    6  3.90  16.46   1     4     4
1   21.0    6  3.90  17.02   1     4     4
2   22.8    4  3.85  18.61   1     4     1
3   21.4    6  3.08  19.44   0     3     1
4   18.7    8  3.15  17.02   0     3     2
5   18.1    6  2.76  20.22   0     3     1
6   14.3    8  3.21  15.84   0     3     4
7   24.4    4  3.69  20.00   0     4     2
8   22.8    4  3.92  22.90   0     4     2
9   19.2    6  3.92  18.30   0     4     4
10  17.8    6  3.92  18.90   0     4     4
11  16.4    8  3.07  17.40   0     3     3
12  17.3    8  3.07  17.60   0     3     3
13  15.2    8  3.07  18.00   0     3     3
14  10.4    8  2.93  17.98   0     3     4
15  10.4    8  3.00  17.82   0     3     4
16  14.7    8  3.23  17.42   0     3     4
17  32.4    4  4.08  19.47   1     4     1
18  30.4    4  4.93  18.52   1     4     2
19  33.9    4  4.22  19.90   1     4     1
20  21.5    4  3.70  20.01   0     3     1
21  15.5    8  2.76  16.87   0     3     2
22  15.2    8  3.15  17.30   0     3     2
23  13.3    8  3.73  15.41   0     3     4
24  19.2    8  3.08  17.05   0     3     2
25  27.3    4  4.08  18.90   1     4     1
26  26.0    4  4.43  16.70   1     5     2
27  30.4    4  3.77  16.90   1     5     2
28  15.8    8  4.22  14.50   1     5     4
29  19.7    6  3.62  15.50   1     5     6
30  15.0    8  3.54  14.60   1     5     8
31  21.4    4  4.11  18.60   1     4     2

In [12]:
df.corr()

mpg       cyl      drat      qsec        am      gear      carb
mpg   1.000000 -0.852162  0.681172  0.418684  0.599832  0.480285 -0.550925
cyl  -0.852162  1.000000 -0.699938 -0.591242 -0.522607 -0.492687  0.526988
drat  0.681172 -0.699938  1.000000  0.091205  0.712711  0.699610 -0.090790
qsec  0.418684 -0.591242  0.091205  1.000000 -0.229861 -0.212682 -0.656249
am    0.599832 -0.522607  0.712711 -0.229861  1.000000  0.794059  0.057534
gear  0.480285 -0.492687  0.699610 -0.212682  0.794059  1.000000  0.274073
carb -0.550925  0.526988 -0.090790 -0.656249  0.057534  0.274073  1.000000

In [13]:
df=pd.read_csv('mtcars.csv')

In [14]:
df.corrwith(df['mpg'])

mpg     1.000000
cyl    -0.852162
disp   -0.847551
hp     -0.776168
drat    0.681172
wt     -0.867659
qsec    0.418684
vs      0.664039
am      0.599832
gear    0.480285
carb   -0.550925
dtype: float64

In [15]:
#### Rank correlation

In [18]:
from scipy.stats import rankdata

In [19]:
x

cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0     6  160.0  110  3.90  2.620  16.46   0   1     4     4
1     6  160.0  110  3.90  2.875  17.02   0   1     4     4
2     4  108.0   93  3.85  2.320  18.61   1   1     4     1
3     6  258.0  110  3.08  3.215  19.44   1   0     3     1
4     8  360.0  175  3.15  3.440  17.02   0   0     3     2
5     6  225.0  105  2.76  3.460  20.22   1   0     3     1
6     8  360.0  245  3.21  3.570  15.84   0   0     3     4
7     4  146.7   62  3.69  3.190  20.00   1   0     4     2
8     4  140.8   95  3.92  3.150  22.90   1   0     4     2
9     6  167.6  123  3.92  3.440  18.30   1   0     4     4
10    6  167.6  123  3.92  3.440  18.90   1   0     4     4
11    8  275.8  180  3.07  4.070  17.40   0   0     3     3
12    8  275.8  180  3.07  3.730  17.60   0   0     3     3
13    8  275.8  180  3.07  3.780  18.00   0   0     3     3
14    8  472.0  205  2.93  5.250  17.98   0   0     3     4
15    8  460.0  215  3.00  5.424  17.82   0   0     3     4
16    8  440.0  230  3.23  5.345  17.42   0   0     3     4
17    4   78.7   66  4.08  2.200  19.47   1   1     4     1
18    4   75.7   52  4.93  1.615  18.52   1   1     4     2
19    4   71.1   65  4.22  1.835  19.90   1   1     4     1
20    4  120.1   97  3.70  2.465  20.01   1   0     3     1
21    8  318.0  150  2.76  3.520  16.87   0   0     3     2
22    8  304.0  150  3.15  3.435  17.30   0   0     3     2
23    8  350.0  245  3.73  3.840  15.41   0   0     3     4
24    8  400.0  175  3.08  3.845  17.05   0   0     3     2
25    4   79.0   66  4.08  1.935  18.90   1   1     4     1
26    4  120.3   91  4.43  2.140  16.70   0   1     5     2
27    4   95.1  113  3.77  1.513  16.90   1   1     5     2
28    8  351.0  264  4.22  3.170  14.50   0   1     5     4
29    6  145.0  175  3.62  2.770  15.50   0   1     5     6
30    8  301.0  335  3.54  3.570  14.60   0   1     5     8
31    4  121.0  109  4.11  2.780  18.60   1   1     4     2

In [30]:
x= np.array([4,11,15,21,28,34,39,35,47,55])
y= np.array([10,22,31,36,48,51,58,61,69,77])
z= np.array([92,83,89,56,61,56,48,41,26,19])
p= np.array([56,44,27,65,38,61,23,75,36,58])

In [31]:
x

array([ 4, 11, 15, 21, 28, 34, 39, 35, 47, 55])

In [32]:
rankdata(x)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  8.,  7.,  9., 10.])

In [33]:
rankdata(y)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [34]:
rankdata(z)

array([10. ,  8. ,  9. ,  5.5,  7. ,  5.5,  4. ,  3. ,  2. ,  1. ])

In [39]:
from scipy.stats import spearmanr,pearsonr

In [40]:
df= pd.DataFrame({
    'X' : x,
    'Y' : y,
    'Z' : z,
    'P' : p
})

In [41]:
spearmanr(x,y)

SignificanceResult(statistic=0.9878787878787878, pvalue=9.307459988955517e-08)

In [42]:
pearsonr(rankdata(x),rankdata(y))

PearsonRResult(statistic=0.9878787878787878, pvalue=9.307459988955525e-08)

In [43]:
df.corr(method='spearman')

X         Y         Z         P
X  1.000000  0.987879 -0.954412 -0.018182
Y  0.987879  1.000000 -0.966570  0.090909
Z -0.954412 -0.966570  1.000000 -0.194530
P -0.018182  0.090909 -0.194530  1.000000

In [44]:
a= np.array([12,15,27,48,56,79])

In [45]:
b= np.array([10,23,33,37,56,89])

In [47]:
spearmanr(a,b)

SignificanceResult(statistic=1.0, pvalue=0.0)

In [48]:
pearsonr(a,b)

PearsonRResult(statistic=0.9603401398228046, pvalue=0.0023281661774570725)

#### Kendall's Tau

In [49]:
from scipy.stats import kendalltau

In [50]:
kendalltau(x,y)

SignificanceResult(statistic=0.9555555555555554, pvalue=5.5114638447971785e-06)

In [51]:
kendalltau(x,z)

SignificanceResult(statistic=-0.8539864924534399, pvalue=0.0006436975254696864)

In [52]:
kendalltau(x,p)

SignificanceResult(statistic=-0.022222222222222223, pvalue=1.0)

In [54]:
df.corr(method='kendall')

X         Y         Z         P
X  1.000000  0.955556 -0.853986 -0.022222
Y  0.955556  1.000000 -0.898933  0.022222
Z -0.853986 -0.898933  1.000000 -0.134840
P -0.022222  0.022222 -0.134840  1.000000

In [55]:
df.corr(method='spearman')

X         Y         Z         P
X  1.000000  0.987879 -0.954412 -0.018182
Y  0.987879  1.000000 -0.966570  0.090909
Z -0.954412 -0.966570  1.000000 -0.194530
P -0.018182  0.090909 -0.194530  1.000000

In [57]:
df.corr()

X         Y         Z         P
X  1.000000  0.988286 -0.959855  0.024336
Y  0.988286  1.000000 -0.952646  0.041168
Z -0.959855 -0.952646  1.000000 -0.200311
P  0.024336  0.041168 -0.200311  1.000000

In [58]:
kendalltau(a,b)

SignificanceResult(statistic=0.9999999999999999, pvalue=0.002777777777777778)