# 

In [1]:
import numpy as np
import matplotlib.pyplot as plt
M = np.array([[5,4,3],[1,7,8],[0,2,3],[7,5,1]])
M


array([[5, 4, 3],
       [1, 7, 8],
       [0, 2, 3],
       [7, 5, 1]])

In [2]:
M.dtype

dtype('int64')

In [3]:
M = np.array([[5,4,3],[1,7,8],[0,2,3],[7,5,1]], dtype = np.int8)
M

array([[5, 4, 3],
       [1, 7, 8],
       [0, 2, 3],
       [7, 5, 1]], dtype=int8)

In [5]:
M.shape


(4, 3)

M.size

In [6]:
M.size

12

In [7]:
M.ndim

2

In [8]:
M[0]

array([5, 4, 3], dtype=int8)

In [9]:
M[0,1]

4

In [11]:
M[1,2]=9
M

array([[5, 4, 3],
       [1, 7, 9],
       [0, 2, 3],
       [7, 5, 1]], dtype=int8)

In [12]:
print(M)

[[5 4 3]
 [1 7 9]
 [0 2 3]
 [7 5 1]]


In [15]:
M.reshape(2,6)


array([[5, 4, 3, 1, 7, 9],
       [0, 2, 3, 7, 5, 1]], dtype=int8)

In [16]:
M.reshape(-1,2)

array([[5, 4],
       [3, 1],
       [7, 9],
       [0, 2],
       [3, 7],
       [5, 1]], dtype=int8)

In [17]:
M.reshape(2,-1)

array([[5, 4, 3, 1, 7, 9],
       [0, 2, 3, 7, 5, 1]], dtype=int8)

In [18]:
M.reshape(-1)

array([5, 4, 3, 1, 7, 9, 0, 2, 3, 7, 5, 1], dtype=int8)

In [19]:
M.flatten()

array([5, 4, 3, 1, 7, 9, 0, 2, 3, 7, 5, 1], dtype=int8)

In [20]:
v1= np.array([3,4,2,1,6,5,4,7,8])
v1.shape

(9,)

In [22]:
v1.reshape(3,3)

array([[3, 4, 2],
       [1, 6, 5],
       [4, 7, 8]])

In [23]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
M.astype(np.float16)

array([[5., 4., 3.],
       [1., 7., 9.],
       [0., 2., 3.],
       [7., 5., 1.]], dtype=float16)

In [25]:
M.astype(np.bool_)

array([[ True,  True,  True],
       [ True,  True,  True],
       [False,  True,  True],
       [ True,  True,  True]])

In [28]:
M.astype(np.unicode_)

array([['5', '4', '3'],
       ['1', '7', '9'],
       ['0', '2', '3'],
       ['7', '5', '1']], dtype='<U4')

In [49]:
for row in M:
    for value in row:
     print(value, end = ' ')
    print()
      
        
    


5 4 3 
1 7 9 
0 2 3 
7 5 1 


In [50]:
var=int(input("Enter a number"))
print(var)

Enter a number 1


1


In [51]:
M.max()

9

In [52]:
M.min()

0

In [53]:
M.mean()

3.9166666666666665

In [54]:
M.std()

2.6601482832520613

In [55]:
M.var()

7.076388888888888

In [56]:
np.median(M)


3.5

In [57]:
M.sum()

47

In [60]:
Z=np.zeros([3,3],dtype=np.int8)
Z

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [63]:
o=np.ones([3,3])
o

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [68]:
S=np.arange(25).reshape(5,5)
S

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [65]:
S[1:3,2:4]

array([[ 7,  8],
       [12, 13]])

In [70]:
S[1:,2:]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

M<4

In [71]:
M>4

array([[ True, False, False],
       [False,  True,  True],
       [False, False, False],
       [ True,  True, False]])

In [72]:
M[M>4]

array([5, 7, 9, 7, 5], dtype=int8)

In [74]:
M[ M%2 ==1]

array([5, 3, 1, 7, 9, 3, 7, 5, 1], dtype=int8)

In [75]:
M1= np.array([[6,8,7],[4,1,3],[5,2,9]])
M1

array([[6, 8, 7],
       [4, 1, 3],
       [5, 2, 9]])

In [85]:
for i in range (M1.shape[0]):
  for j in range (M1.shape[1]):
   if M1[i,j]%2==0:
      M1[i,j]=0
M1     


array([[0, 0, 7],
       [0, 1, 3],
       [5, 0, 9]])

In [86]:
##MATRIX OPERATION


In [101]:
M1= np.array([[5,4,3],[1,7,8],[0,2,3],[7,5,1]], dtype= np.uint8)
M2= np.array([[2,8,1],[0,2,5],[1,9,4],[6,2,6]], dtype= np.uint8)
M1.shape, M2.shape

((4, 3), (4, 3))

In [102]:
M3=M1+M2
M3

array([[ 7, 12,  4],
       [ 1,  9, 13],
       [ 1, 11,  7],
       [13,  7,  7]], dtype=uint8)

In [110]:
M4 = M1-M2
M4

array([[  3, 252,   2],
       [  1,   5,   3],
       [255, 249, 255],
       [  1,   3, 251]], dtype=uint8)

In [111]:
M1+10

array([[15, 14, 13],
       [11, 17, 18],
       [10, 12, 13],
       [17, 15, 11]], dtype=uint8)

In [105]:
M1+[2,3,1]

array([[ 7,  7,  4],
       [ 3, 10,  9],
       [ 2,  5,  4],
       [ 9,  8,  2]])

In [106]:
M1

array([[5, 4, 3],
       [1, 7, 8],
       [0, 2, 3],
       [7, 5, 1]], dtype=uint8)

In [107]:
M2-M1


array([[253,   4, 254],
       [255, 251, 253],
       [  1,   7,   1],
       [255, 253,   5]], dtype=uint8)

In [108]:
abs(M2-M1)

array([[253,   4, 254],
       [255, 251, 253],
       [  1,   7,   1],
       [255, 253,   5]], dtype=uint8)

In [109]:
M1-M2

array([[  3, 252,   2],
       [  1,   5,   3],
       [255, 249, 255],
       [  1,   3, 251]], dtype=uint8)

In [112]:
#SCALAR MULTIPLICATION

In [113]:
3*M

array([[15, 12,  9],
       [ 3, 21, 27],
       [ 0,  6,  9],
       [21, 15,  3]], dtype=int8)

In [114]:
3*(M1+M2)

array([[21, 36, 12],
       [ 3, 27, 39],
       [ 3, 33, 21],
       [39, 21, 21]], dtype=uint8)

In [115]:
3*M1 + 3*M2

array([[21, 36, 12],
       [ 3, 27, 39],
       [ 3, 33, 21],
       [39, 21, 21]], dtype=uint8)

In [116]:
(3+4)*M1

array([[35, 28, 21],
       [ 7, 49, 56],
       [ 0, 14, 21],
       [49, 35,  7]], dtype=uint8)

In [117]:
3*M1 + 4*M1

array([[35, 28, 21],
       [ 7, 49, 56],
       [ 0, 14, 21],
       [49, 35,  7]], dtype=uint8)

In [119]:
3*4*M1,M1*4*3,4*M1*3

(array([[60, 48, 36],
        [12, 84, 96],
        [ 0, 24, 36],
        [84, 60, 12]], dtype=uint8),
 array([[60, 48, 36],
        [12, 84, 96],
        [ 0, 24, 36],
        [84, 60, 12]], dtype=uint8),
 array([[60, 48, 36],
        [12, 84, 96],
        [ 0, 24, 36],
        [84, 60, 12]], dtype=uint8))

In [120]:
-3*M1

array([[-15, -12,  -9],
       [ -3, -21, -24],
       [  0,  -6,  -9],
       [-21, -15,  -3]], dtype=int16)

In [121]:
-(3*M1)

array([[241, 244, 247],
       [253, 235, 232],
       [  0, 250, 247],
       [235, 241, 253]], dtype=uint8)

In [122]:
-1*M1

array([[-5, -4, -3],
       [-1, -7, -8],
       [ 0, -2, -3],
       [-7, -5, -1]], dtype=int16)

In [123]:
#MATRIX MULTIPLICATION

In [125]:
A= np.array([[1,2],[3,4]])
B= np.array([[5,6],[7,8]])
c= np.array([[3,8],[1,6]])
A@(B@c), (A@B)@c

(array([[ 79, 284],
        [179, 644]]),
 array([[ 79, 284],
        [179, 644]]))

In [128]:
A@(B + c), A@B + A@c

(array([[24, 42],
        [56, 98]]),
 array([[24, 42],
        [56, 98]]))

In [129]:
np.transpose(M)

array([[5, 1, 0, 7],
       [4, 7, 2, 5],
       [3, 9, 3, 1]], dtype=int8)

In [130]:
M.reshape(3,4)

array([[5, 4, 3, 1],
       [7, 9, 0, 2],
       [3, 7, 5, 1]], dtype=int8)

In [131]:
M.T

array([[5, 1, 0, 7],
       [4, 7, 2, 5],
       [3, 9, 3, 1]], dtype=int8)

In [132]:
M,M.T.T

(array([[5, 4, 3],
        [1, 7, 9],
        [0, 2, 3],
        [7, 5, 1]], dtype=int8),
 array([[5, 4, 3],
        [1, 7, 9],
        [0, 2, 3],
        [7, 5, 1]], dtype=int8))

In [133]:
A.T + B.T

array([[ 6, 10],
       [ 8, 12]])

In [135]:
(3*M).T ,3* M.T

(array([[15,  3,  0, 21],
        [12, 21,  6, 15],
        [ 9, 27,  9,  3]], dtype=int8),
 array([[15,  3,  0, 21],
        [12, 21,  6, 15],
        [ 9, 27,  9,  3]], dtype=int8))

In [138]:
(A@B).T, B.T@A.T

(array([[19, 43],
        [22, 50]]),
 array([[19, 43],
        [22, 50]]))

In [165]:
rows=(int(input("Enter the no of Rows : ")))
cols=(int(input("Enter the no of Cols : ")))
m0= np.zeros([rows,cols], dtype=np.int16)
for i in range(rows):
    for j in range(cols):
        num=int(input("Enter the Elements : "))
        m0[i,j]=num
print("OG Matrix\n",m0)
print("Transpose Matrix\n",m0.T)
      

Enter the no of Rows :  2
Enter the no of Cols :  3
Enter the Elements :  1
Enter the Elements :  2
Enter the Elements :  3
Enter the Elements :  4
Enter the Elements :  5
Enter the Elements :  5


OG Matrix
 [[1 2 3]
 [4 5 5]]
Transpose Matrix
 [[1 4]
 [2 5]
 [3 5]]


In [166]:
M1= np.array([[5,4,3],[1,7,8],[0,2,3],[7,5,1]], dtype= np.int8)
M2= np.array([[2,8,1],[0,2,5],[1,9,4]], dtype= np.int8)

In [167]:
M1
M2

array([[2, 8, 1],
       [0, 2, 5],
       [1, 9, 4]], dtype=int8)

In [178]:
M1
sum=0


In [184]:
for i in range(M1.shape[0]):
    for j in range(M1.shape[1]):
        if i==j:

            
          sum += M1[i,j]     
print(sum)

90


In [185]:
add=0
for i in range(min(M1.shape)):
    add=M1[i,i]+add
add

15

In [191]:
M1.diagonal().sum()

15

In [189]:
M2.diagonal().sum()


8

In [193]:
M1.trace()

15

In [194]:
M2.trace()

8

In [195]:
np.trace(A @ B), np.trace(B @ A)

(69, 69)

In [197]:
M1.trace(), M.T.trace()

(15, 15)

In [198]:
np.trace(M1 * 3), 3*M1.trace()

(45, 45)

In [199]:
A.trace()+B.trace(), np.trace(A+B)

(18, 18)

In [200]:
np.linalg.det(M2)

-36.0

In [202]:
np.linalg.det(A)

-2.0000000000000004

In [203]:
M2

array([[2, 8, 1],
       [0, 2, 5],
       [1, 9, 4]], dtype=int8)

In [205]:
%precision 2
np.linalg.inv(M2)

array([[ 1.03,  0.64, -1.06],
       [-0.14, -0.19,  0.28],
       [ 0.06,  0.28, -0.11]])

In [207]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [208]:
np.linalg.matrix_rank(M1)

3

In [215]:
M3=np.array([[1,2,3],[4,5,12],[2,7,6]])
np.linalg.matrix_rank(M3) , M3


(2,
 array([[ 1,  2,  3],
        [ 4,  5, 12],
        [ 2,  7,  6]]))

In [216]:
M3[:,0]*3

array([ 3, 12,  6])

In [217]:
np.linalg.matrix_rank(M3)

2

In [218]:
M4=np.array([[1,2,3],[4,8,12],[2,4,6]])

In [219]:
M4

array([[ 1,  2,  3],
       [ 4,  8, 12],
       [ 2,  4,  6]])

In [220]:
np.linalg.matrix_rank(M4)

1

In [224]:
R=np.array([[3,4,5,1,3,8]])

In [225]:
R.shape

(1, 6)

In [226]:
R

array([[3, 4, 5, 1, 3, 8]])

In [227]:
C=np.array([[3,4,5,1,3,8]])
C.reshape(-1,1)

array([[3],
       [4],
       [5],
       [1],
       [3],
       [8]])

In [229]:
C.shape

(1, 6)

In [231]:
C.T

array([[3],
       [4],
       [5],
       [1],
       [3],
       [8]])

In [232]:
R.T

array([[3],
       [4],
       [5],
       [1],
       [3],
       [8]])

In [233]:
C

array([[3, 4, 5, 1, 3, 8]])

In [234]:
C.T

array([[3],
       [4],
       [5],
       [1],
       [3],
       [8]])

In [235]:
R

array([[3, 4, 5, 1, 3, 8]])

In [236]:
R.T

array([[3],
       [4],
       [5],
       [1],
       [3],
       [8]])

In [250]:
S=np.array([[3,4,5],[1,3,8],[9,0,2]])
S

array([[3, 4, 5],
       [1, 3, 8],
       [9, 0, 2]])

In [251]:
def isSquareMatrix(M):
    if M.shape[0]==M.shape[1]:
     print("yeah")
    else:
        print ("No");
        
isSquareMatrix(S)
        

yeah


In [253]:
def isRectangularMatrix(M):
    if M.shape[0]!=M.shape[1]:
     print("yeah")
    else:
        print ("No");
        
isRectangularMatrix(S)
        

No


In [254]:
#Diagonal Matrix
np.random.randint(1,10)

3

In [282]:
#Create Diagonal Square Matrix with n rows/colums
n=(int(input("Enter the no of Rows : ")))

m0= np.zeros([n,n], dtype=np.int16)
m0
for i in range(n):
   m0[i,i]=np.random.randint(1,10)
m0

   


  

Enter the no of Rows :  5


array([[2, 0, 0, 0, 0],
       [0, 4, 0, 0, 0],
       [0, 0, 6, 0, 0],
       [0, 0, 0, 6, 0],
       [0, 0, 0, 0, 2]], dtype=int16)

In [289]:

(m0 >0).flatten().sum()

  

5

In [291]:
def isDiagonalMatrix(M):
    if (m0>0).flatten().sum()==m0.shape[0]:
        return True
    else:
        return False

True

In [293]:
# Identity Matrix

In [311]:
var1=(int(input("Enter the no of Rows : ")))

idn= np.zeros([n,n], dtype=np.int16)
idn
for i in range(n):
   idn[i,i]=1
idn

Enter the no of Rows :  5


array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int16)

In [314]:
def isIdentityMatrix(M):
    if (idn>0).flatten().sum()==idn.shape[0]:
    # if idn[i]==1:
        return True
    else:
        return False
isDiagonalMatrix(M)

True

In [319]:
isIdentityMatrix(M2)

True

In [320]:
#Symmetric Matrix

In [361]:
S = np.array([[2,3,6],[3,4,5],[6,5,9]], dtype = np.int8)
skew = -1 * S


array([[-2, -3, -6],
       [-3, -4, -5],
       [-6, -5, -9]], dtype=int8)

In [323]:
S

array([[2, 3, 6],
       [3, 4, 5],
       [6, 5, 9]], dtype=int8)

In [332]:
S.T

array([[2, 3, 6],
       [3, 4, 5],
       [6, 5, 9]], dtype=int8)

In [334]:
def isSymmetricMatrix(S):
        if S.all()==S.T.all():
            print("True")
        else:
            print("False")
isSymmetricMatrix(M)

True


In [362]:
# def isSkewSymmetricMatrix(S):


#      if skew.all()==S.T.all():
#           print("True")
#      else:
#           print("False")
# isSkewSymmetricMatrix(S)

True


In [363]:
s1= np.array([[0,3],[-3,0]])
s1

array([[ 0,  3],
       [-3,  0]])

In [364]:
-s1.T

array([[ 0,  3],
       [-3,  0]])

In [368]:
def isSkewSymmetricMatrix(S):
    if(-S==S.T).flatten().sum()== S.size():
        return True
    else:
        return False
isSkewSymmetricMatrix(s1)

TypeError: 'int' object is not callable

Enter the no of Rows :  5


array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int16)

In [370]:
idn.T

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int16)

In [372]:
np.linalg.inv(idn)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [375]:
Rm=np.array([[np.cos(50),-np.sin(50)],[np.sin(50),np.cos(50)]])

In [376]:
Rm

array([[ 0.96,  0.26],
       [-0.26,  0.96]])

In [377]:
Rm.T

array([[ 0.96, -0.26],
       [ 0.26,  0.96]])

In [378]:
np.linalg.inv(Rm)

array([[ 0.96, -0.26],
       [ 0.26,  0.96]])

In [379]:
P = np.array([[0,1,0],[1,0,0],[0,0,1]])

In [380]:
P

array([[0, 1, 0],
       [1, 0, 0],
       [0, 0, 1]])

In [381]:
P.T

array([[0, 1, 0],
       [1, 0, 0],
       [0, 0, 1]])

In [382]:
np.linalg.inv(P)

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [383]:
M5=np.array([[5,4,1,3],[8,9,0,3],[2,1,4,9],[7,3,1,4]])
M5

array([[5, 4, 1, 3],
       [8, 9, 0, 3],
       [2, 1, 4, 9],
       [7, 3, 1, 4]])

In [391]:
#Eigenvalues & Eigenvectors
A = np.array([[1,2],[3,4]], dtype=np.int8)

In [392]:
A

array([[1, 2],
       [3, 4]], dtype=int8)

In [393]:
value, vector = np.linalg.eig(A)

In [394]:
value

array([-0.37,  5.37])

In [395]:
vector

array([[-0.82, -0.42],
       [ 0.57, -0.91]])

In [396]:
A @ vector

array([[ 0.31, -2.23],
       [-0.21, -4.89]])

In [397]:
value * vector

array([[ 0.31, -2.23],
       [-0.21, -4.89]])

In [418]:
A = np.array([[1,2,3,4],[3,4,5,6],[1,7,3,9],[8,7,3,5]],dtype=np.int8)
A

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [1, 7, 3, 9],
       [8, 7, 3, 5]], dtype=int8)

In [419]:
value, vectors = np.linalg.eig(A)

In [420]:
value

array([18.33+0.j ,  0.25+0.j , -2.79+2.3j, -2.79-2.3j])

In [421]:
vectors

array([[ 0.29+0.j  ,  0.36+0.j  , -0.06+0.27j, -0.06-0.27j],
       [ 0.5 +0.j  , -0.6 +0.j  ,  0.1 +0.31j,  0.1 -0.31j],
       [ 0.58+0.j  , -0.44+0.j  , -0.69+0.j  , -0.69-0.j  ],
       [ 0.57+0.j  ,  0.56+0.j  ,  0.37-0.45j,  0.37+0.45j]])

In [422]:
A @ vectors



array([[ 5.32e+00+0.j  ,  8.96e-02+0.j  , -4.44e-01-0.9j ,
        -4.44e-01+0.9j ],
       [ 9.21e+00+0.j  , -1.51e-01+0.j  , -1.00e+00-0.63j,
        -1.00e+00+0.63j],
       [ 1.07e+01+0.j  , -1.10e-01+0.j  ,  1.92e+00-1.59j,
         1.92e+00+1.59j],
       [ 1.04e+01+0.j  ,  1.41e-01+0.j  , -3.45e-03+2.1j ,
        -3.45e-03-2.1j ]])

In [423]:
value @ vectors

array([ 2.23+0.03j,  6.05-2.3j , -1.28+3.85j,  0.78-8.73j])

In [425]:
vector.dtype

dtype('float64')